// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChSaz_fAobSfd4adxrsNNxM9JbxHzSPPE',
    appId: '1:200180015309:web:5abc633b185f66dc7e0984',
    messagingSenderId: '200180015309',
    projectId: 'chatapp-463ab',
    authDomain: 'chatapp-463ab.firebaseapp.com',
    storageBucket: 'chatapp-463ab.firebasestorage.app',
    measurementId: 'G-EJ2CXFYP6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxo9ss7rnrv1RItl4zksSqxFCe_M99K0',
    appId: '1:200180015309:android:423f40b894bd567e7e0984',
    messagingSenderId: '200180015309',
    projectId: 'chatapp-463ab',
    storageBucket: 'chatapp-463ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhC9mbDp9HWLrWsudzIxhWkSukkQIoqM',
    appId: '1:200180015309:ios:8e2b44fb9135ec317e0984',
    messagingSenderId: '200180015309',
    projectId: 'chatapp-463ab',
    storageBucket: 'chatapp-463ab.firebasestorage.app',
    iosClientId: '200180015309-g4bab27ssp059lobjdvgmmmg5hssl4jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhC9mbDp9HWLrWsudzIxhWkSukkQIoqM',
    appId: '1:200180015309:ios:8e2b44fb9135ec317e0984',
    messagingSenderId: '200180015309',
    projectId: 'chatapp-463ab',
    storageBucket: 'chatapp-463ab.firebasestorage.app',
    iosClientId: '200180015309-g4bab27ssp059lobjdvgmmmg5hssl4jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChSaz_fAobSfd4adxrsNNxM9JbxHzSPPE',
    appId: '1:200180015309:web:6229298b1c9439bd7e0984',
    messagingSenderId: '200180015309',
    projectId: 'chatapp-463ab',
    authDomain: 'chatapp-463ab.firebaseapp.com',
    storageBucket: 'chatapp-463ab.firebasestorage.app',
    measurementId: 'G-67P7L9M1EF',
  );

}